CompanyProject/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from .views import index, about, services, contactus

admin.site.site_header = "CRM Admin Portal"
admin.site.site_title = "CRM Admin Portal"
admin.site.index_title = "Welcome to CRM Admin Portal"


urlpatterns = [
    path('', index, name='index'),
    path('about/', about, name='about'),
    path('partner/', about, name='partner'),
    path('careers/', about, name='careers'),
    path('terms/', about, name='terms'),
    path('privacy/', about, name='privacy'),
    path('services/', services, name='services'),
    path('services/<slug:service>/', services, name='services'),
    path('support/', include('support.urls')),
    path('customer/', include('customers.urls')),
    path('blogs/', include('blog.urls')),
    path('projects/', include('project.urls')),
    path('announcement/', include('announcement.urls')),
    path('contactus/', contactus, name='contactus'),
    path('startprojects/', index, name='startprojects'),
    path('admin/', admin.site.urls),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blog/urls.py
from django.contrib import admin
from django.urls import path
from .views import SubCategorybyCategoryID, blogs, blogsByCategory, blogsBySearch, blogDetails


app_name="blog"

urlpatterns = [
    path('', blogs, name='index'),
    path('category/<slug:url>/', blogsByCategory, name='category'),
    path('search/', blogsBySearch, name='search'),
    path('details/<slug:url>/', blogDetails, name='details'),
    path('SubCategoryByCategoryID/<int:CategoryID>/',SubCategorybyCategoryID, name="SubCategorybyCategoryID")
]

blog/models.py
from django.db import models
from django.utils.timezone import datetime
from django.contrib.auth import settings
from django.core.validators import FileExtensionValidator

# Create your models here.


class BlogCategory(models.Model):
    objects = models.Manager
    name = models.CharField(max_length=200)
    url = models.CharField(max_length=200, default='', editable=False)
    is_active = models.BooleanField(verbose_name='Is Active', default=True)
    created_on = models.DateField(
        verbose_name='Created On', default=datetime.now, editable=False)
    created_by = models.ForeignKey(
        settings.AUTH_USER_MODEL, on_delete=models.CASCADE, editable=False, default=0)

    class Meta:
        verbose_name_plural = "Blog Categories"

    def __str__(self):
        return self.name


class BlogSubCategory(models.Model):
    objects = models.Manager
    name = models.CharField(max_length=200)
    url = models.CharField(max_length=200, default='', editable=False)
    blog_category = models.ForeignKey(
        BlogCategory, on_delete=models.CASCADE, limit_choices_to={'is_active': True})

    is_active = models.BooleanField(verbose_name='Is Active', default=True)
    created_on = models.DateField(
        verbose_name='Created On', default=datetime.now, editable=False)
    created_by = models.ForeignKey(
        settings.AUTH_USER_MODEL, on_delete=models.CASCADE, editable=False, default=0)

    class Meta:
        verbose_name_plural = "Blog Sub Categories"

    def __str__(self):
        return self.name


class Blog(models.Model):
    objects = models.Manager
    name = models.CharField(max_length=200)
    url = models.CharField(max_length=200, default='', editable=False)
    blog_category = models.ForeignKey(
        BlogCategory, on_delete=models.CASCADE, limit_choices_to={'is_active': True})
    blog_sub_category = models.ForeignKey(
        BlogSubCategory, on_delete=models.CASCADE, limit_choices_to={'is_active': True})

    total_shares = models.IntegerField(default=0)
    total_likes = models.IntegerField(default=0)
    total_comments = models.IntegerField(default=0)

    short_details = models.TextField(max_length=100, default='')
    max_details = models.TextField(default='')

    thumbnail = models.FileField(
        upload_to='blog/', validators=[FileExtensionValidator(
        ['svg', 'png', 'jpg'])], default='')

    banner = models.FileField(
        upload_to='blog/', validators=[FileExtensionValidator(
        ['svg', 'png', 'jpg'])], default='')

    is_active = models.BooleanField(verbose_name='Is Active', default=True, editable=False)
    created_on = models.DateField(
        verbose_name='Created On', default=datetime.now, editable=False)
    created_by = models.ForeignKey(
        settings.AUTH_USER_MODEL, on_delete=models.CASCADE, editable=False, default=0)

    class Meta:
        verbose_name_plural = "Blogs"

    def __str__(self):
        return self.name

blog/views.py
from django.shortcuts import render, HttpResponse
from django.core import serializers
from django.utils.text import slugify
from django.core.paginator import Paginator
# Create your views here.
from .models import BlogSubCategory, BlogCategory, Blog


def SubCategorybyCategoryID(request, CategoryID):
    try:
        __Data = BlogSubCategory.objects.filter(
            blog_category=CategoryID, is_active=True).order_by('name')
        qs_json = serializers.serialize('json', __Data)
        return HttpResponse(qs_json, content_type='application/json')
    except Exception as err:
        return HttpResponse(err)


def blogs(request, type="", id=0):
    try:

        BlogCategoryData = BlogCategory.objects.filter(
            is_active=True).order_by('name')[:4]

        BlogData = Blog.objects.filter(is_active=True)

        paginator = Paginator(BlogData, 6)
        page_number = request.GET.get('page')
        page_obj = paginator.get_page(page_number)

        return render(request, 'blog/blog.html', {'BlogCategoryData': BlogCategoryData, 'page_obj': page_obj,
                                                  'range': paginator.page_range, 'IsLoggedIn': request.session.has_key('LoggedInCust'), })

    except Exception as err:
        print(err)
        return render(request, 'error.html', {'error': err})


def blogsByCategory(request, url=""):
    try:
        BlogCategoryData = BlogCategory.objects.filter(
            is_active=True).order_by('name')[:4]

        blogID = BlogCategory.objects.values('id').filter(url=url)
        BlogData = Blog.objects.filter(
            is_active=True, blog_category=blogID[0]['id'])

        paginator = Paginator(BlogData, 6)
        page_number = request.GET.get('page')
        page_obj = paginator.get_page(page_number)

        return render(request, 'blog/blog.html', {'BlogCategoryData': BlogCategoryData, 'page_obj': page_obj, 
        'range': paginator.page_range, 'IsLoggedIn': request.session.has_key('LoggedInCust'), })

    except Exception as err:
        print(err)
        return render(request, 'error.html', {'error': err})


def blogsBySearch(request):
    try:
        BlogCategoryData = BlogCategory.objects.filter(
            is_active=True).order_by('name')[:4]

        BlogData = Blog.objects.filter(
            is_active=True, name__contains=request.GET['search'])

        paginator = Paginator(BlogData, 6)
        page_number = request.GET.get('page')
        page_obj = paginator.get_page(page_number)

        return render(request, 'blog/blog.html', {'BlogCategoryData': BlogCategoryData, 'page_obj': page_obj,
                                                  'range': paginator.page_range, 'IsLoggedIn': request.session.has_key('LoggedInCust'), 'search': request.GET['search']})

    except Exception as err:
        print(err)
        return render(request, 'error.html', {'error': err})


def blogDetails(request, url=""):
    try:
        BlogCategoryData = BlogCategory.objects.filter(
            is_active=True).order_by('name')[:4]

        categoryID = Blog.objects.values('blog_category').filter(url=url)
        categoryUrl = BlogCategory.objects.values(
            'url').filter(id=categoryID[0]['blog_category'])

        KeepReading = Blog.objects.filter(
            is_active=True, blog_category=categoryID[0]['blog_category']).exclude(url=url)[:3]

        BlogData = Blog.objects.filter(is_active=True, url=url)
        return render(request, 'blog/blogdetails.html', {'BlogData': BlogData, 'BlogCategoryData': BlogCategoryData,
                                                         'Comments': None, 'IsLoggedIn': request.session.has_key('LoggedInCust'), 'KeepReading': KeepReading,
                                                         'categoryUrl': categoryUrl[0]['url']})

    except Exception as err:
        print(err)
        return render(request, 'error.html', {'error': err})

blog/templates/blog/blog.html
{% extends 'base.html' %} {% load static %} {% block stylearea %}
<style></style>
{% endblock %} {% block contentarea %}
<section class="slice slice-lg py-7 bg-cover bg-size--cover" style="background-image:url({% static 'img/backgrounds/img-5.jpg' %})"><span class="mask bg-dark opacity-8"></span>
    <div class="container d-flex align-items-center" data-offset-top=#navbar-main>
        <div class="col py-5">
            <div class="row align-items-center justify-content-center">
                <div class="col-md-7 col-lg-7 text-center">
                    <h1 class="display-4 text-white mb-2"><strong>Our</strong> Blogs</h1><span class="text-white text-sm">#1 blog on web design, news and tools resources on the internet</span></div>
            </div>
        </div>
    </div>
</section>
<section class=border-bottom>
    <div class="container py-3">
        <div class="row align-items-center">
            <div class="col-lg-7 mb-4 mb-lg-0">
                <ul class=nav>
                    <li class=nav-item><a class="nav-link text- active" href="{% url 'blog:index'%}">All</a></li>
                    {% if BlogCategoryData %} {% for dt in BlogCategoryData %}
                    <li class=nav-item><a class="nav-link text- active" href="{% url 'blog:category' dt.url%}">{{dt.name}}</a></li>
                    {% endfor %} {% endif %}
                </ul>
            </div>
            <div class=col-lg-5>
                <form class="rounded-lg border" method="GET" action="{% url 'blog:search'%}">
                    <div class="input-group input-group-merge">
                        <div class=input-group-prepend><span class="input-group-text border-0 pr-2"><i data-feather=search></i></span></div><input type=text name="search" class="form-control border-0 px-1" value="{{search}}" aria-label="Find something" placeholder="Find something...">
                        <div class=input-group-append><span class="input-group-text border-0 py-0 pl-2 pr-1"><button type="submit" class="btn btn-sm btn-primary">Search</button></span></div>
                    </div>
                </form>
            </div>
        </div>
    </div>
</section>
<section class="slice pt-5 pb-7 bg-section-secondary">
    <div class=container>
        <div class=row>
            {% if page_obj %} {% for dt in page_obj %}
            <div class="col-xl-4 col-md-6">
                <div class="card hover-translate-y-n3 hover-shadow-lg overflow-hidden">
                    <div class="position-relative overflow-hidden">
                        <a href="{% url 'blog:details' dt.url %}" class=d-block><img alt="Image placeholder" src="{{dt.thumbnail.url}}" class=card-img-top></a>
                    </div>
                    <div class="card-body py-4"><small class="d-block text-sm mb-2">{{dt.created_on}}</small> <a href="{% url 'blog:details' dt.url %}" class="h5 stretched-link lh-150">{{dt.name}}</a>
                        <p class="mt-3 mb-0 lh-170">{{dt.short_details}}</p>
                    </div>
                    <div class="card-footer border-0 delimiter-top">
                        <div class="row align-items-center">
                            <div class=col-auto><span class="avatar avatar-sm bg-primary rounded-circle">UR</span> <span class="text-sm mb-0 avatar-content">{{ dt.created_by|upper }}</span></div>
                            <div class="col text-right text-right">
                                <div class=actions><a href="{% url 'blog:details' dt.url %}" class=action-item><i data-feather=heart class=mr-1></i> {{dt.total_likes}}</a> <a href="{% url 'blog:details' dt.url %}" class=action-item><i data-feather=message-circle class=mr-1></i> {{dt.total_comments}}</a></div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            {% endfor %}
            <div class="col-md-12 mt-5">
                <nav aria-label="Page navigation example">
                    <ul class="pagination justify-content-center">
                        {% if page_obj.has_previous %}
                        <li class="page-item">
                            <a class="page-link" href="?page=1" tabindex="-1" aria-disabled="true">First</a>
                        </li>
                        <li class="page-item">
                            <a class="page-link" href="?page={{ page_obj.previous_page_number }}" tabindex="-1" aria-disabled="true">Previous</a>
                        </li>
                        {% else %}
                        <li class="page-item disabled">
                            <a class="page-link" href="javascript:void()" tabindex="-1" aria-disabled="true">First</a>
                        </li>
                        <li class="page-item disabled">
                            <a class="page-link" href="javascript:void()" tabindex="-1" aria-disabled="true">Previous</a>
                        </li>
                        {% endif %} {% for page in range %} {% if page_obj.number is page %}
                        <li class="page-item active"><a class="page-link" href="?page={{page}}">{{page}}</a></li>
                        {% else %}
                        <li class="page-item"><a class="page-link" href="?page={{page}}">{{page}}</a></li>
                        {% endif %} {% endfor %} {% if page_obj.has_next %}
                        <li class="page-item">
                            <a class="page-link" href="?page={{ page_obj.next_page_number }}">Next</a>
                        </li>
                        <li class="page-item">
                            <a class="page-link" href="?page={{ page_obj.paginator.num_pages }}">Last</a>
                        </li>
                        {% else %}
                        <li class="page-item disabled">
                            <a class="page-link" href="javascript:void()">Next</a>
                        </li>
                        <li class="page-item disabled">
                            <a class="page-link" href="javascript:void()">Last</a>
                        </li>
                        {% endif %}
                    </ul>
                </nav>
                <!-- <div class="pagination">
                    <span class="step-links">
        {% if page_obj.has_previous %}
            <a href="?page=1">&laquo; first</a>
            <a href="?page={{ page_obj.previous_page_number }}">previous</a>
        {% endif %}

        <span class="current">
            Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}.
        </span> {% if page_obj.has_next %}
                    <a href="?page={{ page_obj.next_page_number }}">next</a>
                    <a href="?page={{ page_obj.paginator.num_pages }}">last &raquo;</a> {% endif %}
                    </span>
                </div> -->
            </div>
            {% else %}
            <div class="col-md-12">
                <div class="alert alert-warning border-0 shadow-lg fade show mb-0">
                    <div class="container text-center">
                        <p class="mb-0">
                            No Blogs found!
                        </p>
                        </button>
                    </div>
                </div>
            </div>
            {% endif %}
        </div>
    </div>
</section>
{% endblock %} {% block scriptarea %}
<script>
</script>
{% endblock %}

blog/templates/blog/blogdetails.html
{% extends 'base.html' %} {% load static %} {% block stylearea %}
<style></style>
{% endblock %} {% block contentarea %} {% if BlogData %} {% for dt in BlogData %}
<div class="min-vh-100 py-9 py-lg-0 bg-cover bg-size--cover" style="background-image:url({{dt.banner.url}})"></div>
<section class="section-half-rounded bg-transparent pt-6 pb-10 mt-n17 zindex-100">
    <div class="jumbotron section-inner left-0 rounded-top-right bg-primary overflow-hidden col-xl-10 col-lg-11"></div>
    <div class=container>
        <div class="row row-grid align-items-center">
            <div class="col-xl-9 col-lg-11 offset-lg-1 offset-xl-2"><a href=# class="badge badge-warning badge-pill">{{dt.blog_category}}</a>
                <h1 class="h2 text-white mt-3 mb-6 pr-5">{{dt.name}}</h1>
            </div>
        </div>
    </div>
</section>
<section class="section-half-rounded bg-transparent py-5 mt-n10 zindex-101">
    <div class="jumbotron section-inner right-0 rounded-0 overflow-hidden col-xl-10 col-lg-12"></div>
    <div class="container pb-6">
        <div class="row row-grid align-items-center">
            <div class="col-xl-8 col-lg-10 offset-xl-2 offset-lg-1">
                <article>
                    <p>{{dt.max_details}}</p>
                </article>
                <div class="row align-items-center mt-7 py-4 border-top border-bottom">
                    <div class="col mb-3 mb-lg-0">
                        <div class="media align-items-center">
                            <div>
                                <a href=# class="avatar rounded-circle mr-3"><img alt="Image placeholder" src="{% static 'img/theme/light/person-2.jpg' %}"></a>
                            </div>
                            <div class=media-body><span class="d-block h6 mb-0">{{dt.created_by|upper}}</span> <span class="text-sm text-muted">Published on {{dt.created_on}}</span></div>
                        </div>
                    </div>
                    <div class=col-auto>
                        <ul class="list-inline mb-0">
                            <li class="list-inline-item pr-4"><a href=# class=text-muted><i data-feather=share class="mr-1 text-muted"></i> {{dt.total_shares}}</a></li>
                            <li class="list-inline-item pr-4"><a href=# class=text-muted><i data-feather=heart class="mr-1 text-muted"></i> {{dt.total_likes}}</a></li>
                            <li class=list-inline-item><a href=# class=text-muted><i data-feather=message-circle class="mr-1 text-muted"></i> {{dt.total_comments}}</a></li>
                        </ul>
                    </div>
                </div>

                <div class=mt-5>
                    <h6 class=mb-4>Comments</h6>
                    {% if IsLoggedIn %} {% if Comments %}
                    <div class="media media-comment"><img alt="Image placeholder" class="rounded-circle shadow mr-4" src="{% static 'img/theme/light/person-3.jpg' %}" style=width:58px>
                        <div class=media-body>
                            <div class="media-comment-bubble left-top">
                                <h6 class=mt-0>Alexis Ren</h6>
                                <p class="text-sm lh-160">Cras sit amet nibh libero, in gravida nulla. Nulla vel metus scelerisque ante sollicitudin. Cras purus odio, vestibulum in vulputate at, tempus viverra turpis.</p>
                                <div class=icon-actions><a href=# class="love active"><i data-feather=heart></i> <span class=text-muted>10 likes</span> </a><a href=#><i data-feather=message-circle></i> <span class=text-muted>1 reply</span></a></div>
                            </div>
                        </div>
                    </div>
                    {% endif %}
                    <div class="media media-comment align-items-center"><img alt="Image placeholder" class="rounded-circle shadow mr-4" src="{% static 'img/theme/light/person-1.jpg' %}" style=width:58px>
                        <div class=media-body>
                            <form class="rounded-lg border">
                                <div class="input-group input-group-lg input-group-merge">
                                    <div class=input-group-prepend><span class="input-group-text border-0 pr-2"><i data-feather=edit-2></i></span></div><input type=text class="form-control border-0 px-1" aria-label="Find something" placeholder="Write a comment...">
                                    <div class=input-group-append><span class="input-group-text border-0 py-0 pl-2 pr-2"><button type=button class="btn btn-sm btn-primary">Post</button></span></div>
                                </div>
                            </form>
                        </div>
                    </div>
                    {% else %}
                    <div class="card hover-scale-105">
                        <div class="card-body row align-items-center">
                            <div class="col-md-6 col">
                                <div class="media align-items-center">
                                    <div><span class="avatar rounded-circle bg-warning text-white mr-4">LG</span></div>
                                    <div class="media-body"><a href="#" class="h6 stretched-link mb-0">Login first to comment here.</a></div>
                                </div>
                            </div>
                            <div class="col-md-6">
                                <hr class="mt-3 mb-4 d-md-none">
                                <div class="row align-items-center">
                                    <div class="col"><a href="#" class="h6 text-sm stretched-link">&nbsp;</a></div>
                                    <div class="col-auto"><a href="#" class="stretched-link"><span class="h6 text-sm ml-3">Clic here to login!</span></a></div>
                                </div>
                            </div>
                        </div>
                    </div>
                    {% endif %}
                </div>

            </div>
        </div>
    </div>
    <div class="shape-container shape-position-bottom"><img alt="Image placeholder" src="{% static 'img/svg/separators/line.svg' %}" class="svg-inject fill-section-secondary"></div>
</section>
{% endfor %} {% if KeepReading %}
<section class="slice slice-lg bg-section-secondary">
    <div class=container>
        <div class="row align-items-center mb-5">
            <div class="col-12 col-md">
                <h3 class="h4 mb-0">Keep reading</h3>
                <p class="mb-0 text-muted">Even more stories from Quick</p>
            </div>
            <div class="col-12 col-md-auto"><a href="{% url 'blog:category' categoryUrl %}" class="btn btn-sm btn-neutral d-none d-md-inline">View all</a></div>
        </div>
        <div class=row>
            {% for dt in KeepReading %}
            <div class="col-xl-4 col-md-6">
                <div class="card hover-translate-y-n3 hover-shadow-lg overflow-hidden">
                    <div class="position-relative overflow-hidden">
                        <a href="{% url 'blog:details' dt.url %}" class=d-block><img alt="Image placeholder" src="{{dt.thumbnail.url}}" class=card-img-top></a>
                    </div>
                    <div class="card-body py-4"><small class="d-block text-sm mb-2">{{dt.created_on}}</small> <a href="{% url 'blog:details' dt.url %}" class="h5 stretched-link lh-150">{{dt.name}}</a>
                        <p class="mt-3 mb-0 lh-170">{{dt.short_details}}</p>
                    </div>
                    <div class="card-footer border-0 delimiter-top">
                        <div class="row align-items-center">
                            <div class=col-auto><span class="avatar avatar-sm bg-primary rounded-circle">UR</span> <span class="text-sm mb-0 avatar-content">{{dt.created_by|upper}}</span></div>
                            <div class="col text-right text-right">
                                <div class=actions><a href="{% url 'blog:details' dt.url %}" class=action-item><i data-feather=heart class=mr-1></i> {{dt.total_likes}}</a> <a href="{% url 'blog:details' dt.url %}" class=action-item><i data-feather=message-circle class=mr-1></i> {{dt.total_comments}}</a></div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            {% endfor %}
        </div>
    </div>
</section>
{% endif %} {% endif %} {% endblock %} {% block scriptarea %}
<script></script>
{% endblock %}