CompanyProject/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from .views import index, about, services, contactus

admin.site.site_header = "CRM Admin Portal"
admin.site.site_title = "CRM Admin Portal"
admin.site.index_title = "Welcome to CRM Admin Portal"


urlpatterns = [
    path('', index, name='index'),
    path('about/', about, name='about'),
    path('partner/', about, name='partner'),
    path('careers/', about, name='careers'),
    path('terms/', about, name='terms'),
    path('privacy/', about, name='privacy'),
    path('services/', services, name='services'),
    path('services/<slug:service>/', services, name='services'),
    path('support/', include('support.urls')),
    path('customer/', include('customers.urls')),
    path('blogs/', include('blog.urls')),
    path('projects/', include('project.urls')),
    path('announcement/', include('announcement.urls')),
    path('contactus/', contactus, name='contactus'),
    path('startprojects/', index, name='startprojects'),
    path('admin/', admin.site.urls),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

announcement/urls.py
from django.contrib import admin
from django.urls import path
from .views import Get, ByType, BySearch


app_name="announcement"

urlpatterns = [
    path('', Get, name='index'),
    path('search/', BySearch, name='search'),
    path('<slug:type>/', ByType, name='type'),
]

blog/urls.py
from django.contrib import admin
from django.urls import path
from .views import SubCategorybyCategoryID, blogs, blogsByCategory, blogsBySearch, blogDetails


app_name="blog"

urlpatterns = [
    path('', blogs, name='index'),
    path('category/<slug:url>/', blogsByCategory, name='category'),
    path('search/', blogsBySearch, name='search'),
    path('details/<slug:url>/', blogDetails, name='details'),
    path('SubCategoryByCategoryID/<int:CategoryID>/',SubCategorybyCategoryID, name="SubCategorybyCategoryID")
]

announcement/models.py
from django.db import models
from django.utils.timezone import datetime
from django.contrib.auth import settings
from django.core.validators import FileExtensionValidator
# Create your models here.


class AnnouncementType(models.Model):
    objects = models.Manager
    name = models.CharField(max_length=200)
    image = models.FileField(upload_to='announcementType/', default='', validators=[FileExtensionValidator(['svg','png','jpg'])])
    url = models.CharField(max_length=200, default='', editable=False)
    is_active = models.BooleanField(verbose_name='Is Active', default=True)
    created_on = models.DateField(
        verbose_name='Created On', default=datetime.now, editable=False)
    created_by = models.ForeignKey(
        settings.AUTH_USER_MODEL, on_delete=models.CASCADE, editable=False, default=0)

    class Meta:
        verbose_name_plural = "Announcement Types"

    def __str__(self):
        return self.name


class Announcement(models.Model):
    objects = models.Manager
    name = models.CharField(max_length=200)
    url = models.CharField(max_length=200, default='', editable=False)

    type = models.ForeignKey(
        AnnouncementType, on_delete=models.CASCADE)

    date = models.DateField(
        verbose_name='Date', default=datetime.now)

    max_details = models.TextField(default='')

    is_active = models.BooleanField(verbose_name='Is Active', default=True)
    created_on = models.DateField(
        verbose_name='Created On', default=datetime.now, editable=False)
    created_by = models.ForeignKey(
        settings.AUTH_USER_MODEL, on_delete=models.CASCADE, editable=False, default=0)

    class Meta:
        verbose_name_plural = "Announcements"

    def __str__(self):
        return self.name

announcement/views.py
from django.shortcuts import render
from .models import AnnouncementType, Announcement
# Create your views here.


def Get(request):
    try:

        TypeData = AnnouncementType.objects.filter(is_active=True)[:4]
       
        AnnouncementData = Announcement.objects.values(
            'id', 'name', 'url', 'category', 'type', 'date', 'max_details', 'created_by').filter(is_active=True)

        count = 0

        for data in AnnouncementData:
            typeurl = AnnouncementType.objects.values(
                'url').filter(is_active=True, id=data['type'])

            AnnouncementData[count]['type__url'] = typeurl[0]['url']
            count += 1

        __context = {'TypeData': TypeData,
                     'AnnouncementData': AnnouncementData, 'IsLoggedIn': request.session.has_key('LoggedInCust'), }
        return render(request, 'announcement/index.html', __context)
    except Exception as err:
        print(err)
        return render(request, 'error.html', {'error': err})


def ByType(request, type=""):
    try:

        TypeData = AnnouncementType.objects.filter(is_active=True)[:4]
        TypeID = AnnouncementType.objects.values(
            'id').filter(is_active=True, url=type)

        AnnouncementData = Announcement.objects.values(
            'id', 'name', 'url', 'type', 'date', 'max_details', 'created_by').filter(is_active=True, type=TypeID[0]['id'])

        count = 0

        typeName = ''
        for data in AnnouncementData:
            typeurl = AnnouncementType.objects.values('name',
                                                      'url').filter(is_active=True, id=data['type'])
            typeName = typeurl[0]['name']
            AnnouncementData[count]['type__url'] = typeurl[0]['url']
            count += 1

        __context = {'TypeData': TypeData,
                     'AnnouncementData': AnnouncementData, 'typeName': typeName,
                     'IsLoggedIn': request.session.has_key('LoggedInCust'), }
        return render(request, 'announcement/index.html', __context)
    except Exception as err:
        print(err)
        return render(request, 'error.html', {'error': err})


def BySearch(request):
    try:

        TypeData = AnnouncementType.objects.filter(is_active=True)[:4]

        AnnouncementData = Announcement.objects.values(
            'id', 'name', 'url', 'type', 'date',
            'max_details', 'created_by').filter(is_active=True, name__contains=request.GET['search'])

        count = 0

        typeName = ''
        for data in AnnouncementData:
            typeurl = AnnouncementType.objects.values('name',
                                                      'url').filter(is_active=True, id=data['type'])
            typeName = typeurl[0]['name']
            AnnouncementData[count]['type__url'] = typeurl[0]['url']
            count += 1

        __context = {'TypeData': TypeData,
                     'AnnouncementData': AnnouncementData,
                     'typeName': typeName, 'search': request.GET['search'],
                     'IsLoggedIn': request.session.has_key('LoggedInCust'), }
        return render(request, 'announcement/index.html', __context)
    except Exception as err:
        print(err)
        return render(request, 'error.html', {'error': err})

announcement/templates/announcement/index.html
{% extends 'base.html' %} {% load static %} {% block stylearea %}
<style></style>
{% endblock %} {% block contentarea %}
<section class="slice slice-lg bg-cover bg-size--cover" style="background-image:url({% static 'img/backgrounds/img-1.jpg' %})"><span class="mask bg-primary opacity-9"></span>
    <div class="container pt-5">
        <div class="row justify-content-center">
            <div class=col-lg-9>
                <h2 class="mb-4 text-center text-white">Search news, events and more.</h2>
                <form method="GET" action="{% url 'announcement:search' %}">
                    <div class="form-group bg-neutral rounded-pill mb-0 px-2 py-2 shadow">
                        <div class=row>
                            <div class=col>
                                <div class="input-group input-group-merge shadow-none">
                                    <div class=input-group-prepend><span class="input-group-text bg-transparent border-0"><i data-feather=search></i></span></div><input name="search" value="{{search}}" type=text class="form-control form-control-flush shadow-none" placeholder="Search for answers ..."></div>
                            </div>
                            <div class=col-auto><button type="submit" class="btn btn-block btn-dark rounded-pill">Search</button></div>
                        </div>
                    </div>
                </form>
            </div>
        </div>
    </div>
    <div class="container position-relative zindex-100">
        <div class="my-5 text-center">
            <h6 class="text-white font-weight-light mb-0">or choose a type to quickly find the answer you need</h6>
        </div>
        {% if TypeData %}
        <div class="row justify-content-center">
            <div class="col-lg-9 col-xl-12">
                <div class=row>
                    {% for data in TypeData %}
                    <div class="col-xl-3 col-lg-6 mb-xl-n8">
                        <div class="card hover-translate-y-n10 hover-shadow-lg">
                            <div class="card-body p-5 text-center">
                                <div class=pb-4><img alt="Image placeholder" src="{{data.image.url}}" class="svg-inject img-fluid" style=height:40px></div>
                                <div class=pt-2><a href="{% url 'announcement:type' data.url  %}" class="h6 stretched-link mb-0">{{ data.name }}</a></div>
                            </div>
                        </div>
                    </div>
                    {% endfor %}
                </div>
            </div>
        </div>
        {% endif %}
    </div>
    <div class="shape-container shape-position-bottom"><svg xmlns=http://www.w3.org/2000/svg viewBox="0 0 1000 100" preserveAspectRatio=none><path d="M 0 0 c 0 0 200 50 500 50 s 500 -50 500 -50 v 101 h -1000 v -100 z"></path></svg></div>
</section>
<section class="slice slice-lg" id=sct-faq>
    <div class=container>
        <div class="row row-grid">
            <div class="col-lg-12 ml-lg-auto">
                {% if AnnouncementData %}
                <div class=mb-5>
                    <h4 class=mb-4 id=theme-integration>{{typeName}}-{{categoryName}}</h4>
                    <div id="{{typeName}}" class="accordion accordion-spaced">
                        {% if AnnouncementData %} {% for data in AnnouncementData %}
                        <div class=card>
                            <div class="card-header py-4" id="{{data.id}}" data-toggle=collapse role=button data-target="#{{data.url}}" aria-expanded=false aria-controls="{{data.url}}">
                                <h6 class=mb-0><i data-feather=file class=mr-3></i>{{data.name}} - {{data.date}}</h6>
                            </div>
                            <div id="{{data.url}}" class=collapse aria-labelledby="{{data.id}}" data-parent="#{{typeName}}">
                                <div class=card-body>
                                    <p>{{data.max_details}}</p>
                                </div>
                            </div>
                        </div>
                        {% endfor %} {% endif %}
                    </div>
                </div>
                {% else %}
                <div class="alert alert-warning border-0 shadow-lg fade show mb-0">
                    <div class="container text-center">
                        <p class="mb-0">
                            No Data found!
                        </p>
                        </button>
                    </div>
                </div>
                {% endif %}
            </div>
        </div>
    </div>
</section>
{% endblock %} {% block scriptarea %}
<script></script>
{% endblock %}